//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtierDLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
